[package]
name = "game"
version = "0.1.0"
edition = "2021"

[lib]
name = "fly_b"

[[bin]]
name = "brick_bird"
path = "./src/main.rs"

[dependencies]
bevy = { version = "0.13", default-features = false, features = ["animation", "bevy_asset", "bevy_audio", "bevy_gilrs", "bevy_scene", "bevy_winit", "bevy_core_pipeline", "bevy_pbr", "bevy_gltf", "bevy_render", "bevy_sprite", "bevy_text", "bevy_ui", "multi-threaded", "png", "hdr", "vorbis", "x11", "bevy_gizmos", "android_shared_stdcxx", "tonemapping_luts", "default_font", "webgl2", "bevy_debug_stepping"] }
bevy-inspector-egui = "0.20.0"
derive_more = "0.99.17"
num-bigint = "0.4.4"
num_enum = "0.7.2"
rand = "0.8.5"
tap = "1.0.1"
thiserror = "1.0.57"
