[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.20.0"
derive_more = "0.99.17"
num-bigint = "0.4.4"
rand = "0.8.5"
tap = "1.0.1"
