[package]
name = "game"
version = "0.1.0"
edition = "2021"

[lib]
name = "fly_b"

[[bin]]
name = "brick_bird"
path = "./src/main.rs"

# Wasm-specific release profile settings
[target.'cfg(target_arch = "wasm32")'.profile.release]
opt-level = 'z'  # Optimize for size
lto = "thin"     # Thin Link Time Optimization

[dependencies]
bevy = { version = "0.11.3" }
bevy-inspector-egui = "0.20.0"
derive_more = "0.99.17"
num-bigint = "0.4.4"
num_enum = "0.7.2"
rand = "0.8.5"
tap = "1.0.1"
thiserror = "1.0.57"
