[package]
name = "game"
version = "0.1.0"
edition = "2021"

[lib]
name = "fly_b"

[dependencies]
bevy = { version = "0.11.3" } # , features = ["dynamic_linking"] }
bevy-inspector-egui = "0.20.0"
derive_more = "0.99.17"
num-bigint = "0.4.4"
num_enum = "0.7.2"
rand = "0.8.5"
tap = "1.0.1"
thiserror = "1.0.57"
